/* ---------------- drag-to-reorder tiles ----------------
 * Pointer-based (not HTML5 DnD, which is reserved for dropping files in).
 * A press only becomes a drag after moving 8px, so click-select and
 * double-click lightbox behavior are untouched. The dragged item takes the
 * drop target's place in the collage order, which is what persists.
 */

import { reorderByHash } from '../core/layout.js';
import { basename } from '../core/paths.js';
import { state, itemsByHash, tiles, collage, persist } from './state.js';
import { render } from './collage.js';

const DRAG_THRESHOLD = 8;
/** {hash, pointerId, startX, startY, active, ghost, targetHash} while a press or drag is in flight */
export let tileDrag = null;
let suppressNextClick = false;
/** performance.now() of the last completed drag; a click right after it is not a double-click */
export let lastDragEndAt = 0;

collage.addEventListener('pointerdown', (event) => {
  if (tileDrag || event.button !== 0 || !event.isPrimary) return;
  if (event.target.closest('.btn-remove')) return;
  const tile = event.target.closest('.tile');
  if (!tile) return;
  document.getElementById('drag-ghost')?.remove(); // never leave two ghosts
  tileDrag = {
    hash: tile.dataset.hash,
    pointerId: event.pointerId,
    startX: event.clientX,
    startY: event.clientY,
    active: false,
    ghost: null,
    targetHash: null
  };
});

window.addEventListener('pointermove', (event) => {
  if (!tileDrag || event.pointerId !== tileDrag.pointerId) return;
  if (!tileDrag.active) {
    const moved = Math.hypot(event.clientX - tileDrag.startX, event.clientY - tileDrag.startY);
    if (moved < DRAG_THRESHOLD) return;
    tileDrag.active = true;
    // capture only once the drag is real: capturing on pointerdown would
    // retarget the compat click and break plain click-select. Capture goes
    // on #collage (survives renders) and guarantees pointerup delivery.
    try {
      collage.setPointerCapture(tileDrag.pointerId);
    } catch {}
    tiles.get(tileDrag.hash)?.classList.add('dragging');
    const ghost = document.createElement('div');
    ghost.id = 'drag-ghost';
    const item = itemsByHash.get(tileDrag.hash);
    ghost.textContent = item ? basename(item.path) : '';
    document.body.appendChild(ghost);
    tileDrag.ghost = ghost;
  }
  // hit-test before touching the ghost's style: elementFromPoint forces a
  // synchronous layout, so reads must come before writes (the ghost is
  // pointer-events:none and never hit-tests itself either way)
  const under = document.elementFromPoint(event.clientX, event.clientY);
  const target = under && under.closest('.tile');
  const targetHash = target && target.dataset.hash !== tileDrag.hash ? target.dataset.hash : null;

  tileDrag.ghost.style.left = `${event.clientX + 12}px`;
  tileDrag.ghost.style.top = `${event.clientY + 14}px`;
  if (targetHash !== tileDrag.targetHash) {
    if (tileDrag.targetHash) tiles.get(tileDrag.targetHash)?.classList.remove('drop-target');
    if (targetHash) tiles.get(targetHash)?.classList.add('drop-target');
    tileDrag.targetHash = targetHash;
  }
});

function endTileDrag(commit) {
  const drag = tileDrag;
  tileDrag = null;
  if (!drag || !drag.active) return;
  try {
    collage.releasePointerCapture(drag.pointerId);
  } catch {}
  // resolve by hash: the original element may have been replaced by a render
  tiles.get(drag.hash)?.classList.remove('dragging');
  if (drag.ghost) drag.ghost.remove();
  if (drag.targetHash) tiles.get(drag.targetHash)?.classList.remove('drop-target');
  lastDragEndAt = performance.now();
  suppressNextClick = true; // the click after pointerup must not select
  setTimeout(() => {
    suppressNextClick = false;
  }, 0); // in case no click follows
  if (commit && drag.targetHash) {
    state.items = reorderByHash(state.items, drag.hash, drag.targetHash);
    render();
    persist();
  }
}

// only the dragging pointer may finish the drag — a stray second touch on a
// touchscreen must not commit or abort a mouse drag (blur stays unconditional)
window.addEventListener('pointerup', (event) => {
  if (tileDrag && event.pointerId !== tileDrag.pointerId) return;
  endTileDrag(true);
});
window.addEventListener('pointercancel', (event) => {
  if (tileDrag && event.pointerId !== tileDrag.pointerId) return;
  endTileDrag(false);
});
// focus loss mid-drag (Alt-Tab, native dialog) delivers no pointerup — abort
// or the ghost and drag state would linger and misfire later
window.addEventListener('blur', () => endTileDrag(false));

// swallow the click generated by a completed drag before tile handlers see it
collage.addEventListener(
  'click',
  (event) => {
    if (suppressNextClick) {
      suppressNextClick = false;
      event.stopPropagation();
    }
  },
  true
);
