'use strict';

/* ---------------- drag-to-reorder tiles ----------------
 * Pointer-based (not HTML5 DnD, which is reserved for dropping files in).
 * A press only becomes a drag after moving 8px, so click-select and
 * double-click lightbox behavior are untouched. The dragged item takes the
 * drop target's place in the collage order, which is what persists.
 */

const DRAG_THRESHOLD = 8;
let tileDrag = null; // {hash, pointerId, startX, startY, active, ghost, targetHash}
let suppressNextClick = false;
let lastDragEndAt = 0;

collage.addEventListener('pointerdown', (e) => {
  if (tileDrag || e.button !== 0 || !e.isPrimary || e.target.closest('.btn-remove')) return;
  const tile = e.target.closest('.tile');
  if (!tile) return;
  document.getElementById('drag-ghost')?.remove(); // never leave two ghosts
  tileDrag = {
    hash: tile.dataset.hash,
    pointerId: e.pointerId,
    startX: e.clientX,
    startY: e.clientY,
    active: false,
    ghost: null,
    targetHash: null
  };
});

window.addEventListener('pointermove', (e) => {
  if (!tileDrag || e.pointerId !== tileDrag.pointerId) return;
  if (!tileDrag.active) {
    if (Math.hypot(e.clientX - tileDrag.startX, e.clientY - tileDrag.startY) < DRAG_THRESHOLD)
      return;
    tileDrag.active = true;
    // capture only once the drag is real: capturing on pointerdown would
    // retarget the compat click and break plain click-select. Capture goes
    // on #collage (survives renders) and guarantees pointerup delivery.
    try {
      collage.setPointerCapture(tileDrag.pointerId);
    } catch {}
    tiles.get(tileDrag.hash)?.classList.add('dragging');
    const ghost = document.createElement('div');
    ghost.id = 'drag-ghost';
    const item = items.find((i) => i.hash === tileDrag.hash);
    ghost.textContent = item ? basename(item.path) : '';
    document.body.appendChild(ghost);
    tileDrag.ghost = ghost;
  }
  // hit-test before touching the ghost's style: elementFromPoint forces a
  // synchronous layout, so reads must come before writes (the ghost is
  // pointer-events:none and never hit-tests itself either way)
  const under = document.elementFromPoint(e.clientX, e.clientY);
  const target = under && under.closest('.tile');
  const targetHash = target && target.dataset.hash !== tileDrag.hash ? target.dataset.hash : null;

  tileDrag.ghost.style.left = `${e.clientX + 12}px`;
  tileDrag.ghost.style.top = `${e.clientY + 14}px`;
  if (targetHash !== tileDrag.targetHash) {
    if (tileDrag.targetHash) tiles.get(tileDrag.targetHash)?.classList.remove('drop-target');
    if (targetHash) tiles.get(targetHash)?.classList.add('drop-target');
    tileDrag.targetHash = targetHash;
  }
});

function endTileDrag(commit) {
  const d = tileDrag;
  tileDrag = null;
  if (!d || !d.active) return;
  try {
    collage.releasePointerCapture(d.pointerId);
  } catch {}
  // resolve by hash: the original element may have been replaced by a render
  tiles.get(d.hash)?.classList.remove('dragging');
  if (d.ghost) d.ghost.remove();
  if (d.targetHash) tiles.get(d.targetHash)?.classList.remove('drop-target');
  lastDragEndAt = performance.now();
  suppressNextClick = true; // the click after pointerup must not select
  setTimeout(() => {
    suppressNextClick = false;
  }, 0); // in case no click follows
  if (commit && d.targetHash) {
    items = reorderByHash(items, d.hash, d.targetHash);
    render();
    persist();
  }
}

// only the dragging pointer may finish the drag — a stray second touch on a
// touchscreen must not commit or abort a mouse drag (blur stays unconditional)
window.addEventListener('pointerup', (e) => {
  if (tileDrag && e.pointerId !== tileDrag.pointerId) return;
  endTileDrag(true);
});
window.addEventListener('pointercancel', (e) => {
  if (tileDrag && e.pointerId !== tileDrag.pointerId) return;
  endTileDrag(false);
});
// focus loss mid-drag (Alt-Tab, native dialog) delivers no pointerup — abort
// or the ghost and drag state would linger and misfire later
window.addEventListener('blur', () => endTileDrag(false));

// swallow the click generated by a completed drag before tile handlers see it
collage.addEventListener(
  'click',
  (e) => {
    if (suppressNextClick) {
      suppressNextClick = false;
      e.stopPropagation();
    }
  },
  true
);
